---
- name: create systemid VG
  lvg:
    vg: "{{ item.name }}"
    pvs: "{{ item.pvs }}"
  with_items:
    - "{{ systemid_vgs }}"
  when: cluster_lvm_control_node | bool

- name: create LVs on systemid VG
  lvol:
    vg: "{{ item.0.name }}"
    lv: "{{ item.1.name }}"
    size: "{{ item.1.size }}"
  with_subelements:
    - "{{ systemid_vgs }}"
    - lvs
  when: cluster_lvm_control_node | bool
