---
- name: create pacemaker activated VG
  lvg:
    vg: "{{ item.name }}"
    pvs: "{{ item.pvs }}"
    vg_options: -cn --addtag pacemaker --config activation{volume_list=['@pacemaker']}
  notify:
    - deactivate VG
    - remove VG tag
  register: vg_created
  with_items:
    - "{{ tagging_vgs }}"
  when: cluster_lvm_control_node | bool

- name: create one LV on pacemaker activated VG
  lvol:
    vg: "{{ item.0.name }}"
    lv: "{{ item.1.name }}"
    size: "{{ item.1.size }}"
    opts: --addtag pacemaker --config "activation{volume_list=['@pacemaker']} global{locking_type=1}"
  notify: deactivate LV
  when: vg_created is changed
  with_subelements:
    - "{{ tagging_vgs }}"
    - lvs
  when: cluster_lvm_control_node | bool
