---
- name: create clustered VG
  lvg: 
    vg: "{{ item.name }}"
    pvs: "{{ item.pvs }}"
    vg_options: -cy
  with_items:
    - "{{ clvm_vgs }}"
  when: cluster_lvm_control_node | bool

- name: create LV on clustered VG
  lvol:
    vg: "{{ item.0.name }}"
    lv: "{{ item.1.name }}"
    size: "{{ item.1.size }}"
  with_subelements:
    - "{{ clvm_vgs }}"
    - lvs
  when: cluster_lvm_control_node | bool
